<?php

global $states;

$states["ES"] = array(
    'C' => __('A Coru&ntilde;a', 'ignitewoo_events'),
    'VI' => __('&Aacute;lava', 'ignitewoo_events'),
    'AB' => __('Albacete', 'ignitewoo_events'),
    'A' => __('Alicante', 'ignitewoo_events'),
    'AL' => __('Almer&iacute;a', 'ignitewoo_events'),
    'O' => __('Asturias', 'ignitewoo_events'),
    'AV' => __('&Aacute;vila', 'ignitewoo_events'),
    'BA' => __('Badajoz', 'ignitewoo_events'),
    'PM' => __('Baleares', 'ignitewoo_events'),
    'B' => __('Barcelona', 'ignitewoo_events'),
    'BU' => __('Burgos', 'ignitewoo_events'),
    'CC' => __('C&aacute;ceres', 'ignitewoo_events'),
    'CA' => __('C&aacute;diz', 'ignitewoo_events'),
    'S' => __('Cantabria', 'ignitewoo_events'),
    'CS' => __('Castell&oacute;n', 'ignitewoo_events'),
    'CE' => __('Ceuta', 'ignitewoo_events'),
    'CR' => __('Ciudad Real', 'ignitewoo_events'),
    'CO' => __('C&oacute;rdoba', 'ignitewoo_events'),
    'CU' => __('Cuenca', 'ignitewoo_events'),
    'GI' => __('Girona', 'ignitewoo_events'),
    'GR' => __('Granada', 'ignitewoo_events'),
    'GU' => __('Guadalajara', 'ignitewoo_events'),
    'SS' => __('Guip&uacute;zcoa', 'ignitewoo_events'),
    'H' => __('Huelva', 'ignitewoo_events'),
    'HU' => __('Huesca', 'ignitewoo_events'),
    'J' => __('Ja&eacute;n', 'ignitewoo_events'),
    'LO' => __('La Rioja', 'ignitewoo_events'),
    'GC' => __('Las Palmas', 'ignitewoo_events'),
    'LE' => __('Le&oacute;n', 'ignitewoo_events'),
    'L' => __('Lleida', 'ignitewoo_events'),
    'LU' => __('Lugo', 'ignitewoo_events'),
    'M' => __('Madrid', 'ignitewoo_events'),
    'MA' => __('M&aacute;laga', 'ignitewoo_events'),
    'ML' => __('Melilla', 'ignitewoo_events'),
    'MU' => __('Murcia', 'ignitewoo_events'),
    'NA' => __('Navarra', 'ignitewoo_events'),
    'OR' => __('Ourense', 'ignitewoo_events'),
    'P' => __('Palencia', 'ignitewoo_events'),
    'PO' => __('Pontevedra', 'ignitewoo_events'),
    'SA' => __('Salamanca', 'ignitewoo_events'),
    'TF' => __('Santa Cruz de Tenerife', 'ignitewoo_events'),
    'SG' => __('Segovia', 'ignitewoo_events'),
    'SE' => __('Sevilla', 'ignitewoo_events'),
    'SO' => __('Soria', 'ignitewoo_events'),
    'T' => __('Tarragona', 'ignitewoo_events'),
    'TE' => __('Teruel', 'ignitewoo_events'),
    'TO' => __('Toledo', 'ignitewoo_events'),
    'V' => __('Valencia', 'ignitewoo_events'),
    'VA' => __('Valladolid', 'ignitewoo_events'),
    'BI' => __('Vizcaya', 'ignitewoo_events'),
    'ZA' => __('Zamora', 'ignitewoo_events'),
    'Z' => __('Zaragoza', 'ignitewoo_events')
); 
